version: "2"
run:
  go: "1.25"
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - copyloopvar
    - dogsled
    - errcheck
    - fatcontext
    - funlen
    - gocritic
    - gocyclo
    - goheader
    - gosec
    - govet
    - ineffassign
    - mirror
    - misspell
    - prealloc
    - protogetter
    - revive
    - staticcheck
    - tagalign
    - unconvert
    - unused
    - whitespace
  settings:
    dupl:
      threshold: 150
    funlen:
      lines: 200
      statements: 200
    gocyclo:
      min-complexity: 36
    gosec:
      excludes:
        - G115
    revive:
      enable-all-rules: false
      rules:
        - name: empty-lines
        - name: use-any
        - name: struct-tag
        - name: context-as-argument
        - name: context-keys-type
        - name: error-return
        - name: error-naming
        - name: exported
          disabled: true
        - name: if-return
        - name: increment-decrement
        - name: var-declaration
        - name: package-comments
          disabled: true
        - name: range
        - name: receiver-naming
        - name: time-naming
        - name: unexported-return
        - name: indent-error-flow
        - name: errorf
        - name: superfluous-else
        - name: unused-parameter
          disabled: true
        - name: unreachable-code
        - name: redefines-builtin-id
    staticcheck:
      checks:
        - -ST1000
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - errcheck
          - funlen
          - gocritic
          - gosec
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
      rewrite-rules:
        - pattern: interface{}
          replacement: any
        - pattern: a[b:len(a)]
          replacement: a[b:]
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
