// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"

	"github.com/go-keg/monorepo/internal/data/example/ent"
)

type CaptchaReply struct {
	ID      string `json:"id"`
	Captcha string `json:"captcha"`
}

type LoginReply struct {
	Token string `json:"token"`
	// 过期时间（秒）
	Exp  int       `json:"exp"`
	User *ent.User `json:"user"`
}

// 消息实体
type Message struct {
	ID          int                `json:"id"`
	Sender      *int               `json:"sender,omitempty"`
	Type        MessageType        `json:"type"`
	Content     string             `json:"content"`
	ContentType MessageContentType `json:"contentType"`
	Metadata    map[string]any     `json:"metadata,omitempty"`
	CreatedAt   time.Time          `json:"createdAt"`
}

type SendMessageInput struct {
	Sender      *int               `json:"sender,omitempty"`
	Type        MessageType        `json:"type"`
	Content     string             `json:"content"`
	ContentType MessageContentType `json:"contentType"`
	Metadata    map[string]any     `json:"metadata,omitempty"`
}

type Subscription struct {
}

type UpdateProfileInput struct {
	Nickname *string `json:"nickname,omitempty"`
	Avatar   *string `json:"avatar,omitempty"`
	Mobile   *string `json:"mobile,omitempty"`
}

// 消息内容类型
type MessageContentType string

const (
	MessageContentTypeText   MessageContentType = "TEXT"
	MessageContentTypeImage  MessageContentType = "IMAGE"
	MessageContentTypeFile   MessageContentType = "FILE"
	MessageContentTypeSystem MessageContentType = "SYSTEM"
	MessageContentTypeCustom MessageContentType = "CUSTOM"
)

var AllMessageContentType = []MessageContentType{
	MessageContentTypeText,
	MessageContentTypeImage,
	MessageContentTypeFile,
	MessageContentTypeSystem,
	MessageContentTypeCustom,
}

func (e MessageContentType) IsValid() bool {
	switch e {
	case MessageContentTypeText, MessageContentTypeImage, MessageContentTypeFile, MessageContentTypeSystem, MessageContentTypeCustom:
		return true
	}
	return false
}

func (e MessageContentType) String() string {
	return string(e)
}

func (e *MessageContentType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MessageContentType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MessageContentType", str)
	}
	return nil
}

func (e MessageContentType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *MessageContentType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e MessageContentType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// 消息类型
type MessageType string

const (
	MessageTypeSystem MessageType = "SYSTEM"
	MessageTypeDirect MessageType = "DIRECT"
)

var AllMessageType = []MessageType{
	MessageTypeSystem,
	MessageTypeDirect,
}

func (e MessageType) IsValid() bool {
	switch e {
	case MessageTypeSystem, MessageTypeDirect:
		return true
	}
	return false
}

func (e MessageType) String() string {
	return string(e)
}

func (e *MessageType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = MessageType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid MessageType", str)
	}
	return nil
}

func (e MessageType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *MessageType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e MessageType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// 用户角色类型
type UserRole string

const (
	// 租户成员
	UserRoleTenantUser UserRole = "TenantUser"
	// 租户Owner
	UserRoleTenantOwner UserRole = "TenantOwner"
	// 系统后台管理员
	UserRoleSystemAdmin UserRole = "SystemAdmin"
)

var AllUserRole = []UserRole{
	UserRoleTenantUser,
	UserRoleTenantOwner,
	UserRoleSystemAdmin,
}

func (e UserRole) IsValid() bool {
	switch e {
	case UserRoleTenantUser, UserRoleTenantOwner, UserRoleSystemAdmin:
		return true
	}
	return false
}

func (e UserRole) String() string {
	return string(e)
}

func (e *UserRole) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = UserRole(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid UserRole", str)
	}
	return nil
}

func (e UserRole) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *UserRole) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e UserRole) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

// 验证码类型
type VerifyCodeType string

const (
	// 忘记密码
	VerifyCodeTypeForgetPassword VerifyCodeType = "ForgetPassword"
	// 注册验证
	VerifyCodeTypeRegister VerifyCodeType = "Register"
)

var AllVerifyCodeType = []VerifyCodeType{
	VerifyCodeTypeForgetPassword,
	VerifyCodeTypeRegister,
}

func (e VerifyCodeType) IsValid() bool {
	switch e {
	case VerifyCodeTypeForgetPassword, VerifyCodeTypeRegister:
		return true
	}
	return false
}

func (e VerifyCodeType) String() string {
	return string(e)
}

func (e *VerifyCodeType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = VerifyCodeType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid VerifyCodeType", str)
	}
	return nil
}

func (e VerifyCodeType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *VerifyCodeType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e VerifyCodeType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
