
key: "${APP_KEY}"
trace:
  endpoint: "${TRACE_ENDPOINT_URL}"
server:
  http:
    addr: 0.0.0.0:8081
    timeout: 30s
data:
  database:
    driver: "mysql"
    dsn: "${CRM_DB_DSN}"

log:
  dir: "./logs/"
  level: "debug"
  maxAge: 30       # day
  rotationTime: 1  # day