apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: golang-admin
    lang: golang
  name: golang-admin
  namespace: ${NAMESPACE}
spec:
  replicas: ${DEFAULT_REPLICAS}
  selector:
    matchLabels:
      app: golang-admin
      lang: golang
  template:
    metadata:
      labels:
        app: golang-admin
        lang: golang
    spec:
      containers:
        - image: ${IMAGE_REGISTRY}/golang-admin:${IMAGE_VERSION}
          imagePullPolicy: ${IMAGE_PULL_POLICY}
          name: golang-admin
          resources:
            requests:
              cpu: ${RESOURCES_REQUESTS_CPU}
              memory: ${RESOURCES_REQUESTS_MEMORY}
          envFrom:
            - configMapRef:
                name: monorepo-env

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: admin-svc
    lang: golang
  name: golang-admin-svc
  namespace: ${NAMESPACE}
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8081
  selector:
    app: golang-admin
    lang: golang
  type: ClusterIP
